name: Test secrets
on:
 push:
 pull_request:
 workflow_dispatch:


jobs:
  test:
   runs-on: ubuntu-latest
   environment: develop

   steps:
     - name: Test simple run
       run: echo "Test simple run"
     - name: Get secrets
       run: echo ${{ secrets.TELEGRAM_BOT_TOKEN }}
     - name: Get variable
       run: echo ${{ vars.NAME }}
